import { IoHomeOutline } from "react-icons/io5";
import { RxDashboard } from "react-icons/rx";

export const sidebarMenus = [
  { title: "Home", src: "/", icon: <IoHomeOutline size={24} /> },
  { title: "Dashboard", src: "/dashboard", icon: <RxDashboard size={24} /> },
];

export const countriesData = [
  "United States of America",
  "Mexico",
  "Nigeria",
  "Lebanon",
  "Russia",
  "Saudi Arabia",
  "Angola",
  "Egypt",
  "South Africa",
  "India",
  "Ukraine",
  "Azerbaijan",
  "China",
  "Colombia",
  "Niger",
  "Libya",
  "Brazil",
  "Mali",
  "Indonesia",
  "Iraq",
  "Iran",
];

export const topicsData = [
  "gas",
  "oil",
  "consumption",
  "market",
  "gdp",
  "war",
  "production",
  "export",
  "battery",
  "biofuel",
  "policy",
  "economy",
  "strategy",
  "robot",
  "growth",
  "economic",
  "energy",
  "food",
  "administration",
  "unemployment",
  "trade",
  "demand",
  "economic growth",
  "industry",
  "capital",
  "worker",
  "tension",
  "terrorism",
  "transport",
  "peak oil",
  "vehicle",
  "tourist",
  "artificial intelligence",
  "climate",
  "power",
  "crisis",
  "ice",
  "population",
  "politics",
  "business",
  "work",
  "coal",
  "gamification",
  "finance",
  "interest rate",
  "risk",
  "inflation",
  "asylum",
  "resource",
  "plastic",
  "electricity",
  "bank",
  "gasoline",
  "car",
  "money",
  "technology",
  "aquaculture",
  "city",
  "investment",
  "revenue",
  "emission",
  "climate change",
  "infrastructure",
  "government",
  "security",
  "software",
  "building",
  "transportation",
  "wealth",
  "clothing",
  "shortage",
  "debt",
  "agriculture",
  "tax",
  "carbon",
  "brexit",
  "workforce",
  "change",
  "automaker",
  "nuclear",
  "3D",
  "water",
  "data",
  "fossil fuel",
  "election",
  "greenhouse gas",
  "information",
  "shale gas",
  "factory",
  "farm",
  "communication",
  "storm",
  "consumer",
  "material",
  "Washington",
  "pollution",
  "fracking",
];

export const sourceData = [
  "EIA",
  "sustainablebrands.com",
  "SBWire",
  "CleanTechnica",
  "TRAC News",
  "Vanguard News",
  "Avi Melamed",
  "WSJ",
  "Abq",
  "Reuters",
  "Star Tribune",
  "EV Obsession",
  "creamermedia",
  "Resilience",
  "TheNews.NG",
  "FashionNetwork.com",
  "Bloomberg Business",
  "Yes Bank",
  "EGYPS",
  "marketrealist",
  "PDQFX news",
  "therobotreport",
  "nextbigfuture",
  "World Bank",
  "Zero Hedge",
  "Rigzone",
  "International Business Times",
  "DOE EIA 2013 Energy Conference",
  "AllAfrica",
  "Energy.gov Website",
  "AMERICAN COUNCIL ON SCIENCE AND HEALTH",
  "The Jakarta Post",
  "Wharton",
  "African Arguments",
  "Business Insider",
  "Convenience Store Decisions",
  "The Next Web",
  "Cii Radio",
  "Global Money Trends",
  "Guardian Sustainable Business",
  "OklahomaMinerals.com",
  "4th Annual Congress and Expo on Biofuels and Bioenergy April 27-28 2017 Dubai UAE",
  "FX Empire",
  "Nexus Conference",
  "Fews Net",
  "Sputnik News",
  "platts",
  "CBO",
  "The Chirographer",
  "THE LEAGUE OF WOMEN VOTERS® OF THE FAIRFAX AREA",
  "Yahoo Finance Canada",
  "Gii Research",
];
